const crops = [
  {id:'pesco',name:'Pesco',emoji:'🍑',risk:'Bolla, oidio, corineo'},
  {id:'melo',name:'Melo',emoji:'🍏',risk:'Ticchiolatura, oidio, carpocapsa'},
  {id:'nashi',name:'Pera Nashi',emoji:'🍐',risk:'Ticchiolatura, psilla, colpo di fuoco'},
  {id:'ciliegio',name:'Ciliegio',emoji:'🍒',risk:'Monilia, mosca, gommosi'},
  {id:'prugno',name:'Prugno',emoji:'🟣',risk:'Monilia, afidi, cidia'},
  {id:'vite',name:'Vite',emoji:'🍇',risk:'Peronospora, oidio, botrite'}
];

const tasks = [
 {id:'rame-autunno',month:10,day:1,emoji:'🍂',title:'Rame dopo caduta foglie',crops:'Tutte le colture',detail:'Intervieni quando è caduto circa il 70–80% delle foglie. Usa solo un prodotto autorizzato e la dose indicata in etichetta.'},
 {id:'potatura-secca',month:1,day:20,emoji:'✂️',title:'Potatura secca',crops:'Melo, nashi, pesco, prugno e vite',detail:'Giornata asciutta, attrezzi disinfettati. Sul ciliegio limita i tagli invernali e preferisci il post-raccolta.'},
 {id:'olio-bianco',month:2,day:15,emoji:'🌱',title:'Olio bianco di fine inverno',crops:'Frutteto',detail:'Solo in riposo vegetativo o secondo etichetta. Non miscelare con zolfo e rispetta l’intervallo indicato dal produttore.'},
 {id:'bolla-pesco',month:3,day:1,emoji:'🍑',title:'Controllo bolla del pesco',crops:'Pesco',detail:'Tratta preventivamente a gemma gonfia, prima dell’apertura. Se le gemme sono già aperte, verifica l’etichetta del prodotto.'},
 {id:'monilia',month:3,day:12,emoji:'🍒',title:'Prevenzione monilia',crops:'Ciliegio e prugno',detail:'Controllo in prefioritura. Evita trattamenti insetticidi durante la fioritura e proteggi gli impollinatori.'},
 {id:'ticchiolatura',month:3,day:15,emoji:'🍏',title:'Ticchiolatura e oidio',crops:'Melo e nashi',detail:'Avvia il monitoraggio da punte verdi/bottoni fiorali, soprattutto con piogge e bagnatura fogliare.'},
 {id:'vite-primo',month:4,day:5,emoji:'🍇',title:'Primo controllo vite',crops:'Vite',detail:'A germogli di circa 10–15 cm controlla rischio peronospora e oidio. Non trattare automaticamente: valuta meteo, sintomi e bollettino locale.'},
 {id:'scacchiatura',month:5,day:5,emoji:'🌿',title:'Scacchiatura e spollonatura',crops:'Vite',detail:'Elimina germogli sterili o mal posizionati e polloni dal tronco; conserva quelli necessari alla forma di allevamento.'},
 {id:'diradamento',month:5,day:25,emoji:'🍎',title:'Diradamento frutti',crops:'Melo, nashi, pesco e prugno',detail:'Rimuovi i frutti in eccesso dopo la cascola naturale per migliorare pezzatura e ridurre rotture.'},
 {id:'potatura-verde',month:6,day:15,emoji:'✂️',title:'Potatura verde',crops:'Vite e fruttiferi vigorosi',detail:'Cimatura e sfemminellatura moderate. Evita defogliazioni eccessive sul lato più esposto al sole.'},
 {id:'mosca-ciliegio',month:5,day:1,emoji:'🪰',title:'Monitoraggio mosca del ciliegio',crops:'Ciliegio',detail:'Installa trappole cromotropiche prima dell’invaiatura. Intervieni solo in base alle catture e con prodotti autorizzati.'},
 {id:'raccolta-potatura-ciliegio',month:7,day:1,emoji:'🍒',title:'Potatura del ciliegio dopo raccolta',crops:'Ciliegio',detail:'Esegui tagli contenuti in periodo asciutto, rimuovendo rami malati, secchi o che si incrociano.'}
];

const guides = {
 pesco:{title:'Potatura del pesco',steps:['Individua i rami misti di un anno: sono quelli produttivi da conservare.','Elimina rami secchi, malati, troppo verticali o diretti verso il centro.','Accorcia o rinnova gradualmente i rami che hanno già prodotto.','Mantieni la chioma aperta e ben illuminata; evita tagli drastici.'],link:'https://www.youtube.com/results?search_query=potatura+pesco+rami+misti'},
 melo:{title:'Potatura del melo',steps:['Riconosci lamburde e brindilli, che portano buona parte della produzione.','Togli succhioni verticali, rami sovrapposti e quelli rivolti verso l’interno.','Evita di eliminare troppe lamburde; dirada invece le zone troppo fitte.','Conserva una struttura equilibrata con branche ben distanziate.'],link:'https://www.youtube.com/results?search_query=potatura+melo+lamburde+brindilli'},
 nashi:{title:'Potatura del nashi',steps:['Mantieni una struttura simile al pero, con branche aperte e illuminate.','Rimuovi succhioni e rami verticali vigorosi.','Conserva rami fruttiferi giovani e rinnova gradualmente quelli esauriti.','Evita potature eccessive, che stimolano vegetazione a discapito dei frutti.'],link:'https://www.youtube.com/results?search_query=potatura+pero+nashi'},
 ciliegio:{title:'Potatura del ciliegio',steps:['Preferisci il periodo successivo alla raccolta, con tempo asciutto.','Limita i tagli grossi perché il ciliegio cicatrizza con difficoltà.','Elimina secco, rami malati, incrociati o troppo interni.','Disinfetta gli attrezzi e proteggi i tagli importanti secondo buone pratiche locali.'],link:'https://www.youtube.com/results?search_query=potatura+ciliegio+dopo+raccolta'},
 prugno:{title:'Potatura del prugno',steps:['Distingui rami di un anno e mazzetti di maggio.','Rimuovi succhioni, rami secchi e quelli che chiudono il centro.','Rinnova gradualmente le branche produttive senza svuotare la chioma.','Esegui tagli netti e non lasciare monconi.'],link:'https://www.youtube.com/results?search_query=potatura+prugno+mazzetti+di+maggio'},
 vite:{title:'Potatura della vite',steps:['Individua il legno di un anno nato su legno di due anni.','Scegli speroni o capi a frutto in base alla forma di allevamento.','Lascia il carico di gemme adatto al vigore della pianta.','Lega i capi a frutto senza strozzarli e rimuovi il legno inutile.'],link:'https://www.youtube.com/results?search_query=potatura+vite+guyot+cordone+speronato'}
};

let view='today';
const app=document.getElementById('app');
const dialog=document.getElementById('taskDialog');
const form=document.getElementById('taskForm');
const logs=()=>JSON.parse(localStorage.getItem('agricare_logs')||'[]');
const saveLogs=x=>localStorage.setItem('agricare_logs',JSON.stringify(x));
const fmt=d=>new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d);
function nextDate(t){const now=new Date();let d=new Date(now.getFullYear(),t.month-1,t.day,9);if(d<now)d=new Date(now.getFullYear()+1,t.month-1,t.day,9);return d}
function daysTo(d){return Math.ceil((d-new Date())/86400000)}
function render(){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); if(view==='today')today(); if(view==='crops')cropList(); if(view==='calendar')calendar(); if(view==='log')logView(); if(view==='more')more();}
function today(){const sorted=[...tasks].sort((a,b)=>nextDate(a)-nextDate(b));const soon=sorted.slice(0,4);app.innerHTML=`<section class="hero"><p class="date">${fmt(new Date())}</p><h2>Controlla prima di intervenire</h2><p>Le date sono promemoria: lo stadio della pianta e l’etichetta del prodotto hanno sempre la precedenza.</p></section><div class="section-title"><h2>Prossime attività</h2><span>${soon.length} promemoria</span></div><div class="cards">${soon.map(taskCard).join('')}</div><div class="section-title"><h2>Avvertenza</h2></div><div class="notice">Non applicare dosi generiche. Usa esclusivamente prodotti autorizzati per coltura e avversità, seguendo etichetta, tempi di carenza, dispositivi di protezione e norme locali.</div>`;bindTasks()}
function taskCard(t){const d=nextDate(t), days=daysTo(d);return `<article class="card task"><div class="emoji">${t.emoji}</div><div><h3>${t.title}</h3><p>${t.crops}<br>${d.toLocaleDateString('it-IT',{day:'numeric',month:'long'})} · tra ${days} giorni</p></div><button class="mini task-open" data-id="${t.id}">Apri</button></article>`}
function cropList(){app.innerHTML=`<section class="hero"><p class="date">Schede operative</p><h2>Le tue colture</h2><p>Trattamenti, rischi principali e guide di potatura.</p></section><div class="crop-grid">${crops.map(c=>`<button class="crop-card" data-crop="${c.id}"><span>${c.emoji}</span><h3>${c.name}</h3><p>${c.risk}</p></button>`).join('')}</div>`;document.querySelectorAll('[data-crop]').forEach(b=>b.onclick=()=>cropDetail(b.dataset.crop))}
function cropDetail(id){const c=crops.find(x=>x.id===id),g=guides[id], related=tasks.filter(t=>t.crops.toLowerCase().includes(c.name.toLowerCase())||t.crops.includes('Tutte')||t.crops.includes('Frutteto'));app.innerHTML=`<button class="secondary" id="back">← Colture</button><section class="hero" style="margin-top:14px"><p class="date">Scheda coltura</p><h2>${c.emoji} ${c.name}</h2><p>Rischi principali: ${c.risk}</p></section><div class="section-title"><h2>Attività</h2></div><div class="cards">${related.map(taskCard).join('')}</div><div class="section-title"><h2>${g.title}</h2></div><article class="card guide"><ul>${g.steps.map(x=>`<li>${x}</li>`).join('')}</ul><a href="${g.link}" target="_blank" rel="noopener">Apri video dimostrativi ↗</a></article>`;document.getElementById('back').onclick=()=>{view='crops';render()};bindTasks()}
function calendar(){const by={};tasks.forEach(t=>(by[t.month]??=[]).push(t));app.innerHTML=`<section class="hero"><p class="date">Calendario annuale</p><h2>Lavori programmati</h2><p>Apri un’attività per registrarla come eseguita.</p></section>${Object.keys(by).sort((a,b)=>a-b).map(m=>`<section class="month"><h3>${new Date(2027,m-1,1).toLocaleDateString('it-IT',{month:'long'})}</h3><div class="cards">${by[m].sort((a,b)=>a.day-b.day).map(taskCard).join('')}</div></section>`).join('')}`;bindTasks()}
function logView(){const all=logs().sort((a,b)=>new Date(b.date)-new Date(a.date));app.innerHTML=`<section class="hero"><p class="date">Storico locale</p><h2>Registro lavori</h2><p>I dati restano salvati su questo iPhone/browser.</p></section><div class="cards">${all.length?all.map(x=>`<article class="card"><h3>${x.title}</h3><p style="color:var(--muted);margin-top:6px">${new Date(x.date+'T12:00').toLocaleDateString('it-IT')} · ${x.product||'Nessun prodotto indicato'}</p><p style="margin-top:10px">${x.notes||''}</p></article>`).join(''):'<div class="empty">Nessuna attività registrata.</div>'}</div>`}
function more(){app.innerHTML=`<section class="hero"><p class="date">Impostazioni</p><h2>AgriCare v1</h2><p>Prima versione installabile, utilizzabile anche offline dopo il primo caricamento.</p></section><div class="cards"><article class="card"><h3>Installazione su iPhone</h3><p style="margin-top:8px;line-height:1.5;color:var(--muted)">Apri il sito in Safari, tocca Condividi, quindi “Aggiungi alla schermata Home”.</p></article><article class="card"><h3>Backup</h3><p style="margin-top:8px;line-height:1.5;color:var(--muted)">In questa versione i dati sono locali. Una futura versione potrà sincronizzarli nel cloud.</p></article></div>`}
function bindTasks(){document.querySelectorAll('.task-open').forEach(b=>b.onclick=()=>openTask(b.dataset.id))}
function openTask(id){const t=tasks.find(x=>x.id===id);document.getElementById('taskId').value=id;document.getElementById('dialogTitle').textContent=t.title;document.getElementById('doneDate').value=new Date().toISOString().slice(0,10);document.getElementById('product').value='';document.getElementById('notes').value=t.detail;dialog.showModal()}
form.addEventListener('submit',e=>{e.preventDefault();const t=tasks.find(x=>x.id===document.getElementById('taskId').value);const all=logs();all.push({title:t.title,date:document.getElementById('doneDate').value,product:document.getElementById('product').value,notes:document.getElementById('notes').value});saveLogs(all);dialog.close();view='log';render()});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBtn').classList.remove('hidden')});document.getElementById('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}}
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
render();
